name: Production Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean & Setup
        run: |
          rm -rf android
          flutter create --platforms=android --org com.kainuwa .
          flutter pub get
          
          # [NEW] Inject Cleartext Traffic bypass for HTTP API endpoints
          sed -i 's/<application/<application android:usesCleartextTraffic="true"/g' android/app/src/main/AndroidManifest.xml

      - name: Setup Icons & Package Name
        run: |
          flutter pub add --dev flutter_launcher_icons
          dart run flutter_launcher_icons

      - name: Build Production Artifacts
        run: |
          flutter build apk --release
          flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Alumni_HYSM_APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: Alumni_HYSM_AAB
          path: build/app/outputs/bundle/release/app-release.aab
